### ISSUE TITLE
Slight mismatches between book and code

### ISSUE THREAD

**Issue by dtilson** [the-deep-learners/deep-learning-illustrated#5]
Enjoying the book. 

Found a couple of small issues with using TensorBoard according to the instructions on page 152 of the book.

1. The `--logdir='logs/deep-net'`   option in step 2 should be `--logdir='work/notebooks/logs/deep-net'` as the code in the notebook creates the logs directory in the notebooks directory. 
2. The `docker run` command needs -p 6006:6006 added to allow a browser on the host machine to access TensorBoard  e.g. `docker run -v %cd%:/home/jovyan/work -it --rm -p 8888:8888 -p 6006:6006 dli-stack`. Could make the changes in the rundocker.bat and rundocker.sh files.

**Comment by jonkrohn** [comment]
Glad to hear you're enjoying the book, @dtilson 😄 

With respect to your first point, is this not addressed by footnote 38 on page 152? 

With respect to your second point, you're quite right! I'm making your suggested changes presently.
