### ISSUE TITLE
backpropagation on appendix B

### ISSUE THREAD

**Issue by ricky-lim** [the-deep-learners/deep-learning-illustrated#6]
Hi Jon,

I would like to double check with formula part of **B.6** at the appendix, please. defining the gradient of the activation function w.r.t. z

![CodeCogsEqn](https://user-images.githubusercontent.com/10878392/71660604-dce4ca00-2d4b-11ea-9d78-57e59ae97183.gif)

Given **B.2**, I thought part of **B.6** should be:

![CodeCogsEqn (1)](https://user-images.githubusercontent.com/10878392/71660651-07368780-2d4c-11ea-93f8-c1c7c5517ccd.gif)

Please check if it is correct and please do let me know otherwise.

Thank you in advance for your time and consideration.

Cheers

**Comment by jonkrohn** [comment]
Thanks for this, @ricky-lim ! Thoughts, @grantbey ?

**Comment by grantbey** [comment]
Hi @ricky-lim,

Thanks for this - you're absolutely correct. That term should, in fact, be:

![](https://user-images.githubusercontent.com/10878392/71660651-07368780-2d4c-11ea-93f8-c1c7c5517ccd.gif).

Thus, the equation in **B.6** should be corrected to:

![image](https://user-images.githubusercontent.com/7283550/71829057-bedfd800-3071-11ea-8ce8-75372cbc706d.png)

Thanks for the catch. We'll submit the typo to the publishers for correction.

Well done!
